version: '3.4'
services:
    fizzbuzz:
        build:
            # the right Dockerfile path is injected via environment variable
            dockerfile: ${D_PATH:-Dockerfile}
            context: .
        depends_on:
            - postgres
        ports:
            - 3000:3000
        # temporary hack because sometimes the service fizzbuzz up before postgres is up
        restart: unless-stopped
        environment:
            # App config
            - PORT=3000
            - ENV=debug
            # Postgres config
            - PG_HOST=postgres
            - PG_USER=fizzbuzz
            - PG_NAME=fizzbuzz
            - PG_PASSWORD=fizzbuzz
        volumes:
            # needed in Dockerfile.dev for file watch mode
            - ./:/go/src

    postgres:
        container_name: postgres
        image: postgres:13
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=fizzbuzz
            - POSTGRES_PASSWORD=fizzbuzz
        # volumes:
        #    - ${HOME}/.data/postgres/fizzbuzz:/var/lib/postgresql/data:delegated
