version: '3.4'
services:
    fizzbuzz:
        build:
            context: .
        ports:
            - 3000:3000
            - 2345:2345
        environment:
            - PORT=3000
            - ENV=debug
        volumes:
            - ./:/go/cmd/app
